import { ver } from "https://javascriptextras.github.io/javascriptextras/jsx/main.js";
import { decimalAdd, decimalSub, decimalMul, decimalDiv } from "https://javascriptextras.github.io/javascriptextras/jsx/main.js";
import { replaceHTML, replaceATTRIB } from "https://javascriptextras.github.io/javascriptextras/jsx/dom.js";
console.log("JSX Version " + ver());
alert(decimalAdd(1, 0.4));
alert(decimalSub(0.3, 0.2));
alert(decimalMul(0.3, 0.4));
alert(decimalDiv(0.3, 0.2));
replaceHTML("tst", "Yeah!");
replaceATTRIB("tst", "style", "color: red");
